version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - run: sudo pip install molecule cookiecutter
      - run: cookiecutter --no-input gh:becksteadn/cookiecutter-molecule
      - run: cd test_role
      - run: molecule lint
