---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu
    image: ubuntu:16.04
  - name: centos
    image: centos:7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ['701', '703']
verifier:
  name: goss
  lint:
    name: yamllint
